mina:
  server:
    ip: 192.168.0.11    # 监听指定 IP
    port: 61005           # 监听端口
    boss-threads: 4      # Acceptor 线程数（建议 = CPU核心数）
    worker-core-threads: 8    # Worker 线程数（建议 = CPU核心数×2）
    worker-max-threads: 32    # Worker 线程数（建议 = CPU核心数×2）
    idle-timeout: 60     # 空闲超时（秒）
    buffer-size: 2048    # 读写缓冲区大小
core-server:
  url: http://192.168.0.11:27022

local-server:
  url: http://192.168.0.11:27022
  node:
    ident: http://192.168.0.11:27022/
  sql: select * from ac_cntrl..控制器表 where 节点标识 = '%s'

spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.11:1433;databaseName=ac_cntrl;encrypt=true;trustServerCertificate=true
    username: sa
    password: Acsys_0000
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 5000  # 30秒超时
      idle-timeout: 600000       # 10分钟空闲超时
      max-lifetime: 1800000       # 30分钟最大存活
      maximum-pool-size: 10       # 最大连接数
